version: '2.4'

services:
  reactive:
    build: reactive-servlet/reactive
    mem_limit: 350m
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy
  
  mysql:
    image: mysql:8.0
    platform: "linux/x86_64"
    mem_limit: 350m
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=reactive
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
    healthcheck:
      test: "/usr/bin/mysql -uuser -p1234 --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10