drop table if exists user CASCADE;
create table user (
    id bigint generated by default as identity,
    name varchar(255),
    property double,
    primary key (id)
);

drop table if exists stocktrade CASCADE;
create table stocktrade (
    id bigint generated by default as identity,
    timestamp timestamp,
    company_name varchar(255),
    price decimal(19,2),
    trade_quantity int,
    trade_action varchar(255),
    user_id bigint,
    primary key (id)
);